# Generated by Django 3.2.20 on 2023-07-21 09:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_favouriteitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavouriteItem',
            new_name='FavoriteItem',
        ),
    ]
